name: Hello World Action
on: 
        push:
                branches: [ "main" ]
        workflow_dispatch:
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Hello World
                          run: echo -e '#include <iostream>\n int main(){std::cout<<"Hello World";}' > helloWorldAction.cpp
                        - run: g++ helloWorldAction.cpp && ./a.out
