name: Hello World Action
on: [push]
jobs:
        Create-Hello-World:
                runs-on: ubuntu-latest
                steps:
                        run: echo "This job was triggered by a ${{ github.event_name }} event."
                        run: make clean
                        run: make hello
